// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulosTaller.Models;

#nullable disable

namespace ModulosTaller.Migrations
{
    [DbContext(typeof(TallerMotosDbContext))]
    partial class TallerMotosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModulosTaller.Models.Agendamiento", b =>
                {
                    b.Property<int>("IdAgendamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgendamiento"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdHorario")
                        .HasColumnType("int");

                    b.Property<int?>("IdMoto")
                        .HasColumnType("int");

                    b.HasKey("IdAgendamiento")
                        .HasName("PK__Agendami__8516393DC4B8E90B");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdHorario");

                    b.HasIndex("IdMoto");

                    b.ToTable("Agendamientos");
                });

            modelBuilder.Entity("ModulosTaller.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__A3C02A1030306DE5");

                    b.ToTable("CategoriaProductos");
                });

            modelBuilder.Entity("ModulosTaller.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdCliente")
                        .HasName("PK__Clientes__D594664212B0B659");

                    b.HasIndex(new[] { "Documento" }, "UQ__Clientes__Documento")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ModulosTaller.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<bool>("EstaAnulada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.HasKey("IdCompra")
                        .HasName("PK__Compras__0A5CDB5C716AAA18");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("ModulosTaller.Models.CompraDetalle", b =>
                {
                    b.Property<int>("IdCompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompraDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdCompraDetalle")
                        .HasName("PK__CompraDe__A1B840C5C2BC30EF");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdProducto");

                    b.ToTable("CompraDetalle", (string)null);
                });

            modelBuilder.Entity("ModulosTaller.Models.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<string>("DiaSemana")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeOnly?>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time");

                    b.HasKey("IdHorario")
                        .HasName("PK__Horarios__1539229B0F26AE6A");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("ModulosTaller.Models.Motocicleta", b =>
                {
                    b.Property<int>("IdMoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMoto"));

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdMoto")
                        .HasName("PK__Motocicl__33CED5FBEDA1A059");

                    b.HasIndex("IdCliente");

                    b.HasIndex(new[] { "Placa" }, "UQ__Motocicl__8310F99D2178C770")
                        .IsUnique();

                    b.ToTable("Motocicletas");
                });

            modelBuilder.Entity("ModulosTaller.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPermiso")
                        .HasName("PK__Permisos__0D626EC88C70CD31");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("ModulosTaller.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__09889210FAD937BE");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ModulosTaller.Models.Proveedore", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdProveedor")
                        .HasName("PK__Proveedo__E8B631AF3DEC2399");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("ModulosTaller.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__2A49584C9AE85A0A");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ModulosTaller.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__5B65BF97AE0A9458");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Correo" }, "UQ__Usuarios__60695A19A7DCDF4A")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ModulosTaller.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<DateTime>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdCompra")
                        .HasColumnType("int");

                    b.HasKey("IdVenta")
                        .HasName("PK__Ventas__BC1240BDFC61093A");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdCompra");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("ModulosTaller.Models.VentaDetalle", b =>
                {
                    b.Property<int>("IdVentaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVentaDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdVentaDetalle")
                        .HasName("PK__VentaDet__2787211D41EF6E96");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("VentaDetalle", (string)null);
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int");

                    b.HasKey("IdRol", "IdPermiso")
                        .HasName("PK__RolPermi__BA9F7EA063D4DD87");

                    b.HasIndex("IdPermiso");

                    b.ToTable("RolPermiso", (string)null);
                });

            modelBuilder.Entity("ModulosTaller.Models.Agendamiento", b =>
                {
                    b.HasOne("ModulosTaller.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Agendamientos")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__Agendamie__IdCli__59FA5E80");

                    b.HasOne("ModulosTaller.Models.Horario", "IdHorarioNavigation")
                        .WithMany("Agendamientos")
                        .HasForeignKey("IdHorario")
                        .HasConstraintName("FK__Agendamie__IdHor__5BE2A6F2");

                    b.HasOne("ModulosTaller.Models.Motocicleta", "IdMotoNavigation")
                        .WithMany("Agendamientos")
                        .HasForeignKey("IdMoto")
                        .HasConstraintName("FK__Agendamie__IdMot__5AEE82B9");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdHorarioNavigation");

                    b.Navigation("IdMotoNavigation");
                });

            modelBuilder.Entity("ModulosTaller.Models.Compra", b =>
                {
                    b.HasOne("ModulosTaller.Models.Proveedore", "IdProveedorNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdProveedor")
                        .HasConstraintName("FK__Compras__IdProve__4BAC3F29");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("ModulosTaller.Models.CompraDetalle", b =>
                {
                    b.HasOne("ModulosTaller.Models.Compra", "IdCompraNavigation")
                        .WithMany("CompraDetalles")
                        .HasForeignKey("IdCompra")
                        .HasConstraintName("FK__CompraDet__IdCom__4E88ABD4");

                    b.HasOne("ModulosTaller.Models.Producto", "IdProductoNavigation")
                        .WithMany("CompraDetalles")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__CompraDet__IdPro__4F7CD00D");

                    b.Navigation("IdCompraNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("ModulosTaller.Models.Motocicleta", b =>
                {
                    b.HasOne("ModulosTaller.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Motocicleta")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__Motocicle__IdCli__5535A963");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("ModulosTaller.Models.Producto", b =>
                {
                    b.HasOne("ModulosTaller.Models.CategoriaProducto", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK__Productos__IdCat__45F365D3");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("ModulosTaller.Models.Usuario", b =>
                {
                    b.HasOne("ModulosTaller.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .HasConstraintName("FK__Usuarios__IdRol__403A8C7D");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("ModulosTaller.Models.Venta", b =>
                {
                    b.HasOne("ModulosTaller.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK__Ventas__IdClient__5FB337D6");

                    b.HasOne("ModulosTaller.Models.Compra", "IdCompraNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("IdCompra")
                        .HasConstraintName("FK__Ventas__IdCompra__60A75C0F");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdCompraNavigation");
                });

            modelBuilder.Entity("ModulosTaller.Models.VentaDetalle", b =>
                {
                    b.HasOne("ModulosTaller.Models.Producto", "IdProductoNavigation")
                        .WithMany("VentaDetalles")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__VentaDeta__IdPro__6477ECF3");

                    b.HasOne("ModulosTaller.Models.Venta", "IdVentaNavigation")
                        .WithMany("VentaDetalles")
                        .HasForeignKey("IdVenta")
                        .HasConstraintName("FK__VentaDeta__IdVen__6383C8BA");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("RolPermiso", b =>
                {
                    b.HasOne("ModulosTaller.Models.Permiso", null)
                        .WithMany()
                        .HasForeignKey("IdPermiso")
                        .IsRequired()
                        .HasConstraintName("FK__RolPermis__IdPer__3C69FB99");

                    b.HasOne("ModulosTaller.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__RolPermis__IdRol__3B75D760");
                });

            modelBuilder.Entity("ModulosTaller.Models.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ModulosTaller.Models.Cliente", b =>
                {
                    b.Navigation("Agendamientos");

                    b.Navigation("Motocicleta");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ModulosTaller.Models.Compra", b =>
                {
                    b.Navigation("CompraDetalles");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ModulosTaller.Models.Horario", b =>
                {
                    b.Navigation("Agendamientos");
                });

            modelBuilder.Entity("ModulosTaller.Models.Motocicleta", b =>
                {
                    b.Navigation("Agendamientos");
                });

            modelBuilder.Entity("ModulosTaller.Models.Producto", b =>
                {
                    b.Navigation("CompraDetalles");

                    b.Navigation("VentaDetalles");
                });

            modelBuilder.Entity("ModulosTaller.Models.Proveedore", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("ModulosTaller.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ModulosTaller.Models.Venta", b =>
                {
                    b.Navigation("VentaDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
